node {
    def app
    agent { dockerfile true }

    stage('Clone repository') {
        /* Let's make sure we have the repository cloned to our workspace */

        checkout scm
        
    }

    stage('Build image') {
        /* This builds the actual image; synonymous to
         * docker build on the command line */
        app = docker.build("wrighter/todo", "./web/")
    }
 /* 
    stage('Test image') {
       

        // app.inside {
            sh 'echo "Tests passed"'
        // }
    }
     */
    stage('Push image') {
    //    Finally, we'll push the image with two tags:
    //      * First, the incremental build number from Jenkins
    //      * Second, the 'latest' tag.
    //      * Pushing multiple tags is cheap, as all the layers are reused.
        docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials-mos') {
            app.push("${env.BUILD_NUMBER}")
            app.push("latest")
        }
    }

    stage('Deploy'){
        sh 'ssh root@80.211.147.114 -o StrictHostKeyChecking=no docker ps'
    }

}
